Description: >
  Provides extra headers for static content served by cloudfront. Must be set up in us-east-1

Parameters:
  EnvironmentName:
    Type: String
  LambdaCodeBucket:
    Type: String
    Default: "solvestack-lambda-code"

Resources:
  ResponseHeaderLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Sub "ResponseHeaders/${EnvironmentName}/index.js.zip"
      Role: !GetAtt ResponseHeaderRole.Arn
      Runtime: nodejs10.x
      Handler: index.handler
      Timeout: 2

  ResponseHeaderFunctionVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref ResponseHeaderLambda
      Description: !Sub "Response Headers for the ${EnvironmentName} Domain"

  ResponseHeaderRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - edgelambda.amazonaws.com
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

Outputs:
  ResponseHeaderLambda:
    Value: !Ref ResponseHeaderFunctionVersion
