---
AWSTemplateFormatVersion: 2010-09-09

Description: >
  A basic CloudFormation template for an ElasticSearch Service Domain.

Parameters:
  DomainName:
    Description: User defined Elasticsearch Domain name
    Type: String
  ElasticsearchVersion:
    Description: User defined Elasticsearch Version
    Type: String
  InstanceType:
    Type: String
    Default: 't2.medium.elasticsearch'
  Subnet:
    Description: Choose which subnet the ES domain should be deployed to
    Type: String
  EsSecurityGroup:
    Type: String
  EnvironmentName:
    Type: String
Resources:
  ElasticsearchDomain:
    Type: AWS::Elasticsearch::Domain
    Properties:
      DomainName: !Ref DomainName
      ElasticsearchVersion: !Ref ElasticsearchVersion
      ElasticsearchClusterConfig:
        InstanceCount: '3'
        InstanceType: !Ref InstanceType
      EBSOptions:
        EBSEnabled: 'true'
        Iops: 0
        VolumeSize: 20
        VolumeType: 'gp2'
      SnapshotOptions:
        AutomatedSnapshotStartHour: '0'
      AccessPolicies:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: '*'
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: 'true'
      Tags:
        - Key: project
          Value: !Ref EnvironmentName
        - Key: ansible_group
          Value: elasticsearch
      VPCOptions:
        SubnetIds:
          - !Ref Subnet
        SecurityGroupIds:
          - !Ref EsSecurityGroup



Outputs:
  DomainArn:
    Value: !GetAtt ElasticsearchDomain.DomainArn
  DomainEndpoint:
    Value: !GetAtt ElasticsearchDomain.DomainEndpoint
